export const LOG_ACTIONS = {
  USER_LOGIN: "user_login",
  USER_REGISTER: "user_register",
  USER_LOGOUT: "user_logout",
  PROFILE_UPDATE: "profile_update",
  POST_CREATE: "post_create",
  POST_UPDATE: "post_update",
  POST_DELETE: "post_delete",
  ACHIEVEMENT_CREATE: "achievement_create",
  ACHIEVEMENT_UPDATE: "achievement_update",
  ACHIEVEMENT_DELETE: "achievement_delete",
  CERTIFICATION_UPLOAD: "certification_upload",
  CERTIFICATION_UPDATE: "certification_update",
  CERTIFICATION_DELETE: "certification_delete",
  REVIEW_SUBMIT: "review_submit",
  REVIEW_APPROVE: "review_approve",
  REVIEW_REJECT: "review_reject",
  PROJECT_CREATE: "project_create",
  PROJECT_UPDATE: "project_update",
  PROJECT_DELETE: "project_delete",
  ADMIN_ACCESS: "admin_access",
} as const;
export type LogAction = (typeof LOG_ACTIONS)[keyof typeof LOG_ACTIONS];
export const LOG_ACTION_LABELS: Record<LogAction, string> = {
  [LOG_ACTIONS.USER_LOGIN]: "User Login",
  [LOG_ACTIONS.USER_REGISTER]: "User Registration",
  [LOG_ACTIONS.USER_LOGOUT]: "User Logout",
  [LOG_ACTIONS.PROFILE_UPDATE]: "Profile Update",
  [LOG_ACTIONS.POST_CREATE]: "Post Created",
  [LOG_ACTIONS.POST_UPDATE]: "Post Updated",
  [LOG_ACTIONS.POST_DELETE]: "Post Deleted",
  [LOG_ACTIONS.ACHIEVEMENT_CREATE]: "Achievement Created",
  [LOG_ACTIONS.ACHIEVEMENT_UPDATE]: "Achievement Updated",
  [LOG_ACTIONS.ACHIEVEMENT_DELETE]: "Achievement Deleted",
  [LOG_ACTIONS.CERTIFICATION_UPLOAD]: "Certificate Uploaded",
  [LOG_ACTIONS.CERTIFICATION_UPDATE]: "Certificate Updated",
  [LOG_ACTIONS.CERTIFICATION_DELETE]: "Certificate Deleted",
  [LOG_ACTIONS.REVIEW_SUBMIT]: "Review Submitted",
  [LOG_ACTIONS.REVIEW_APPROVE]: "Review Approved",
  [LOG_ACTIONS.REVIEW_REJECT]: "Review Rejected",
  [LOG_ACTIONS.PROJECT_CREATE]: "Project Created",
  [LOG_ACTIONS.PROJECT_UPDATE]: "Project Updated",
  [LOG_ACTIONS.PROJECT_DELETE]: "Project Deleted",
  [LOG_ACTIONS.ADMIN_ACCESS]: "Admin Access",
};